# Generated by Django 6.1.2 on 2026-10-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 yrs)'), ('mid', 'Mid Level (2-5 yrs)'), ('senior', 'Senior Level (5+ yrs)'), ('lead', 'Lead / Manager'), ('executive', 'Executive')], default='mid', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='List key requirements')),
                ('skills_required', models.CharField(blank=True, help_text='Comma-separated skills', max_length=500)),
                ('salary_range', models.CharField(blank=True, help_text='e.g. $80k–$120k', max_length=100)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('removed', 'Removed by Admin')], default='active', max_length=20)),
                ('referrals_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(limit_choices_to={'role': 'alumni'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
    ]
