# Generated by Django 6.1.2 on 2026-10-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('admin_outcome', models.CharField(blank=True, choices=[('', 'Not Yet Reviewed'), ('hired', 'Hired'), ('interviewed', 'Interviewed'), ('not_hired', 'Not Hired'), ('dropped', 'Candidate Dropped Out')], default='', max_length=20)),
                ('cover_note', models.TextField(help_text='Why are you a good fit? (max 1000 chars)', max_length=1000)),
                ('alumni_note', models.TextField(blank=True, help_text="Alumni's note to the requester")),
                ('admin_notes', models.TextField(blank=True, help_text='Admin internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('alumni', models.ForeignKey(limit_choices_to={'role': 'alumni'}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests_received', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to='jobs.jobposting')),
                ('requester', models.ForeignKey(limit_choices_to={'role': 'job_seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Request',
                'verbose_name_plural': 'Referral Requests',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'requester')},
            },
        ),
    ]
